server:
  port: 8099

spring:
#  main:
#    web-application-type: none
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://101.43.191.204:15432/ai-rag-knowledge
    type: com.zaxxer.hikari.HikariDataSource
  ai:
    mcp:
      client:
        request-timeout: 360s
        sse:
          connections:
            mcp-server-csdn:
              url: http://127.0.0.1:8101
            mcp-server-weixin:
              url: http://127.0.0.1:8102
#        stdio:
#          servers-configuration: classpath:/config/mcp-servers-config-4.json
    openai:
      base-url: https://apis.itedus.cn
      api-key: sk-0lAgl6jPaKiBI2ek799e02319d1c4112BfE3A51a497c2a72
      chat:
        options:
          model: gpt-4.1-mini
      embedding-model: text-embedding-ada-002
      embedding:
        options:
          num-batch: 1536
    ollama:
      base-url: http://a4358e346f944d7dbf4b-deepseek-r1-llm-api.gcs-xy1a.jdcloud.com/
      mode:
      embedding-model: nomic-embed-text
      embedding:
        options:
          num-batch: 768

logging:
  level:
    root: info
  config: classpath:logback-spring.xml