server:
  port: 8090

spring:
  #  main:
  #    web-application-type: none
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://192.168.1.109:15432/ai-rag-knowledge
    type: com.zaxxer.hikari.HikariDataSource
  ai:
    mcp:
      client:
        request-timeout: 360s
        sse:
          connections:
            mcp-server-csdn:
              url: http://113.46.142.175:8101
            mcp-server-weixin:
              url: http://113.46.142.175:8102
    #        stdio:
    #          servers-configuration: classpath:/config/mcp-servers-config-4.json
    openai:
      base-url: https://apis.itedus.cn
      api-key: sk-BtNEoFEb1xj3jjck4851050468Df4c19916692C955F5C787
      chat:
        options:
          model: gpt-4.1-mini
      embedding-model: text-embedding-ada-002
      embedding:
        options:
          num-batch: 1536
    ollama:
      base-url: http://58a39caa684c41bf9bed-deepseek-r1-llm-api.gcs-xy1a.jdcloud.com/
      mode:
      embedding-model: nomic-embed-text
      embedding:
        options:
          num-batch: 768

logging:
  level:
    root: info
  config: classpath:logback-spring.xml